### ISSUE TITLE
JMAP: Refresh the JWT token upon 403?

### ISSUE THREAD

**Issue by chibenwa** [OpenPaaS-Suite/esn-frontend-inbox#415]
We noticed some 403 errors linked to the usage by INBOX of expired tokens.

It would be nice to handle 403 errors and refresh the JWT token + resume the API call.

cc @chamerling 

Also, how is the JWT token renewal handled? Do the front compare it itself to its clock? This would be impacted by clock skew and might explain the current behaviour...

**Comment by chamerling** [comment]
I guess it is not renewed (this is something I did not worked on, but pretty sure it is not...)
Anyway, to manage this, clients and servers usually add a delay between token expiration date and current one.

**Comment by chibenwa** [comment]
>  Anyway, to manage this, clients and servers usually add a delay between token expiration date and current one.

Yes and as a fallback upon 403 clients renew the token rather than failing....

**Comment by chibenwa** [comment]
```
  | io.jsonwebtoken.ExpiredJwtException: JWT expired at 2021-04-16T19:55:57Z. Current time: 2021-04-17T01:07:09Z, a difference of 18672834 milliseconds.  Allowed clock skew: 0 milliseconds. 	at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:385) 	at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:481) 	at io.jsonwebtoken.impl.DefaultJwtParser.parseClaimsJws(DefaultJwtParser.java:541) 	at org.apache.james.jwt.JwtTokenVerifier.parseToken(JwtTokenVerifier.java:88) 	at org.apache.james.jwt.JwtTokenVerifier.extractLogin(JwtTokenVerifier.java:64) 	at org.apache.james.jwt.JwtTokenVerifier.verify(JwtTokenVerifier.java:52) 	at org.apache.james.jmap.jwt.JWTAuthenticationStrategy.lambda$createMailboxSession$3(JWTAuthenticationStrategy.java:65) 	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:113) 	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127) 	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onNext(FluxFilterFuseable.java:118) 	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1789) 	at reactor.core.publisher.MonoCallable.subscribe(MonoCallable.java:61) 	at reactor.core.publisher.Mono.subscribe(Mono.java:4046) 	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:448) 	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onSubscribe(FluxConcatMap.java:218) 	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:164) 	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:86) 	at reactor.core.publisher.FluxFromMonoOperator.subscribe(FluxFromMonoOperator.java:83) 	at reactor.core.publisher.FluxUsing.subscribe(FluxUsing.java:114) 	at reactor.core.publisher.Mono.subscribe(Mono.java:4046) 	at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run(MonoSubscribeOn.java:126) 	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) 	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) 	at java.base/java.lang.Thread.run(Thread.java:834)
-- | --
```

Bingo!

@vincent-zurczak  @tanandy can you please check for clocks between the emaily and trinity cluster nodes? (just to be sure sorry OVH makes me paranoid these days...)

**Comment by tanandy** [comment]
@chibenwa for which tenant ? is it op@Linagora ?

**Comment by chibenwa** [comment]
> @chibenwa for which tenant ? is it op@Linagora ?

Yes

**Comment by tanandy** [comment]
ok simple docker vm no cluster

clock seems good 
esn vm +james vm

```
      Local time: Sat 2021-04-17 07:40:25 UTC
  Universal time: Sat 2021-04-17 07:40:25 UTC
        RTC time: Sat 2021-04-17 07:40:25
       Time zone: Etc/UTC (UTC, +0000)
 Network time on: yes
NTP synchronized: yes
 RTC in local TZ: no
```

Is is the jwt created on a different TZ ?

do we have to check dbs? (mongo, es, ... ?)

**Comment by chibenwa** [comment]
> do we have to check dbs? (mongo, es, ... ?)

No need. JWT is validated at the applicative level.

> Is is the jwt created on a different TZ ?

@chamerling @fabienmoyon what is the ESN backend doing? 

James uses its system clock (so default server clock) for verifying the token. Dates are expressed in seconds since EPOCH UTC. 

From: https://github.com/jwtk/jjwt/issues/122

```
The JWT RFC specification requires datetimes to be represented in seconds since epoch, never milliseconds. See the NumericDate definition here:

https://tools.ietf.org/html/rfc7519#page-6
      A JSON numeric value representing the number of seconds from
      1970-01-01T00:00:00Z UTC until the specified UTC date/time,
      ignoring leap seconds.
```

Our JWT parsing lib looks good...

**Comment by chibenwa** [comment]
BTW @fabienmoyon we are speaking about the JMAP JWT token not the WebAdmin one. The behaviour might defer...

**Comment by chamerling** [comment]
I guess OP is doing nothing on its side. To be confirmed by @fabienmoyon

**Comment by alagane** [comment]
I have no idea how to reproduce this on purpose.

**Comment by chibenwa** [comment]
Well James logs on openpaas.linagora.com are full of these examples...
